### ISSUE TITLE
Error during rosinstall src /opt/ros/melodic tiago_dual_public-melodic.rosinstall

### ISSUE THREAD

**Issue by prajwalthakur** [pal-robotics/tiago_dual_tutorials#1]
Hello everyone I am stuck at a step for installation of tiago++ simulation for ROS MELODIC :
I was following the steps mentioned in rosWiki  for  Installing TIAGo++ Simulation.
[installation_for_tiago](http://wiki.ros.org/Robots/TIAGo%2B%2B/Tutorials/Installation/Tiago%2B%2BSimulation)
After executing the step {rosinstall src /opt/ros/melodic tiago_dual_public-melodic.rosinstall}
I got the the error as shown in the attached figure:
![error_tiago](https://user-images.githubusercontent.com/42039745/78765624-dfd40400-79a5-11ea-9aae-ec3a555b52a7.png)
This is an error of cloning ros_control folder from melodic-devel branch. 
Please help

**Comment by v-lopez** [comment]
Sorry there was an error in the .rosinstall file, an incorrect branch for ros_control repo

It's been fixed here: https://github.com/pal-robotics/tiago_dual_tutorials/commit/6e538fe30856adf103f61fbfdf632585770297a0

Please download the file again and run continue with the tutorial installation.

**Comment by prajwalthakur** [comment]
thanks problem has been resolved now. closing the issue
