### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by dnandha** [pal-robotics/tiago_dual_tutorials#5]
When building the docker image i get the following error in step 8/10:
```
...
Get:20 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2185 kB]
Fetched 23.6 MB in 2s (12.3 MB/s)
Reading package lists...
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tiago_dual_controller_configuration: Cannot locate rosdep definition for [joint_impedance_trajectory_controller]
The command '/bin/sh -c apt-get update && rosdep install --from-paths src --ignore-src -y --rosdistro melodic --skip-keys="${ROSDEP_IGNORE}"' returned a non-zero code: 1
```

Appending "joint_impedance_trajectory_controller" to the rosdep ignore-list in the Dockerfile prevents this error, but I'm not sure if it's the correct solution.

**Comment by YueErro** [comment]
Hi @dnandha,

thank you for pointing this issue out. We have added the `joint_impedance_trajectory_controller` to the ignore-list, as you suggested, and the docker image can be built without errors now.

**Comment by dnandha** [comment]
Thank you
